export const ADD_USER_NOTIFICATION = " ADD_USER_NOTIFICATION";
export const ADD_SESSION_NOTIFICATION = "ADD_SESSION_NOTIFICATION";
export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";
export const UPDATE_USER_NOTIFICATION = " UPDATE_USER_NOTIFICATION";
export const UPDATE_SESSION_NOTIFICATION = "UPDATE_SESSION_NOTIFICATION";
export const UPDATE_INTERVIEW_NOTIFICATION = "UPDATE_INTERVIEW_NOTIFICATION";
