export const RESET_USER_DETAILS = "RESET_USER_DETAILS";
export const SET_ERROR_GETTING_USER_DETAILS = "SET_ERROR_GETTING_USER_DETAILS";
export const SET_IS_GETTING_USER_DETAILS = "SET_IS_GETTING_USER_DETAILS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
