export const RESET_USER_DETAILS = "RESET_USER_DETAILS";
export const SET_ERROR_GETTING_USER_DETAILS = "SET_ERROR_GETTING_USER_DETAILS";
export const SET_IS_GETTING_USER_DETAILS = "SET_IS_GETTING_USER_DETAILS";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const SET_SHOW_LOGOUT_MODAL = "SET_SHOW_LOGOUT_MODAL";
export const SET_SELECTED_MODULE_ = "SET_SELECTED_MODULE_";
