export const DATA_SOURCE = [
  {
    id: 1,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 2,
    UserName: "Anika",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: false,
  },
  {
    id: 3,
    UserName: "Nihil",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 4,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 5,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 6,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 7,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 8,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 9,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2011",
    status: true,
  },
  {
    id: 10,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 11,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 12,
    UserName: "Mike",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
  {
    id: 13,
    UserName: "Mike last",
    email: "example@gmail.com",
    mobile: 9999999999,
    access: "All",
    createdOn: "10/10/2010",
    status: true,
  },
];

export const COMPANY_DATA_SOURCE = [
  {
    id: 1,
    companyName: "Google",
    entity: "Corporate",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: true,
  },
  {
    id: 2,
    companyName: "Microsoft",
    entity: "Corporate",
    city: "Hyderabad",
    phoneNumber: "+91-1234 5678 21",
    status: false,
  },
  {
    id: 3,
    companyName: "Farmaco",
    entity: "Non-corporate",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: true,
  },
  {
    id: 4,
    companyName: "Phylo",
    entity: "Firm of Chartered Accountants",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: true,
  },
  {
    id: 5,
    companyName: "Daffodils",
    entity: "Corporate",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: false,
  },
  {
    id: 6,
    companyName: "Sprinklr",
    entity: "Non-corporate",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: true,
  },
  {
    id: 7,
    companyName: "Sprinklr",
    entity: "Corporate",
    city: "Hyderabad",
    phoneNumber: "+91-1234 5678 21",
    status: true,
  },
  {
    id: 8,
    companyName: "Sprinklr",
    entity: "Corporate",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: true,
  },
  {
    id: 9,
    companyName: "Sprinklr",
    entity: "Corporate",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: false,
  },
  {
    id: 10,
    companyName: "Sprinklr",
    entity: "Corporate",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: false,
  },
  {
    id: 11,
    companyName: "Google",
    entity: "Corporate",
    city: "Gurgaon",
    phoneNumber: "+91-1234 5678 21",
    status: false,
  },
];

export const ACCESS_FILTER_DATA = [
  {
    id: 1,
    name: "Access 1",
    options: [
      { optionId: 1, str: "All" },
      { optionId: 2, str: "Placements" },
      { optionId: 3, str: "CA Jobs" },
    ],
  },
];

export const COMPANIES_FILTER_DATA = [
  {
    id: 1,
    name: "Entity",
    isSelected: false,
    options: [
      { optionId: 1, str: "Corporate" },
      { optionId: 2, str: "Non-corporate" },
      { optionId: 3, str: "Firm of Chartered Accountants" },
    ],
  },
  {
    id: 2,
    name: "More than 10 Partners",
    isSelected: false,
  },
];

export const SESSION_DETAILS = {
  name: "Jadyn Bartoletti",
  session_start_date: "2023-12-19T05:11:46.000000Z",
  session_end_date: "2023-12-19T05:11:46.000000Z",
  nature_of_service: "nature",
  perform_invoice_no_format: "AugSept-*****-2023",
  examination_session_period: ["May 2023", "November 2023"],
  gmcs_completion_date: "2023-12-19T05:11:46.000000Z",
  membership_completion_date: "2023-12-19T05:11:46.000000Z",
  article_completion_from_date: "2023-12-19T05:11:46.000000Z",
  bank_ac_no: "88896186",
  hsn_sac_code: "1791686",
  bank_ac_ifsc: "SBIN0005836",
  status: true,
  created_at: "2023-12-19T05:11:46.000000Z",
  updated_at: "2023-12-19T05:11:46.000000Z",
};

export const INITIAL_CENTRE_DETAILS = {
  centre_name: "",
  centre_code: "",
  status: 1,
};

export const MOCK_INTERVIEW = [
  {
    id: 1,
    sNo: "1",
    centreName: "Ghaziabad-I",
    totalStudentBooked: "12",
  },
  {
    id: 2,
    sNo: "2",
    centreName: "Ghaziabad-II",
    totalStudentBooked: "12",
  },
  {
    id: 3,
    sNo: "3",
    centreName: "Meerut-I",
    totalStudentBooked: "12",
  },
  {
    id: 4,
    sNo: "4",
    centreName: "Meerut-II",
    totalStudentBooked: "12",
  },
  { id: 5, sNo: "5", centreName: "Delhi-I", totalStudentBooked: "12" },
  {
    id: 6,
    sNo: "6",
    centreName: "Delhi-II",
    totalStudentBooked: "12",
  },
  {
    id: 7,
    sNo: "7",
    centreName: "Ahmedabad-I",
    totalStudentBooked: "12",
  },
  {
    id: 8,
    sNo: "8",
    centreName: "Ahmedabad-II",
    totalStudentBooked: "12",
  },
  {
    id: 9,
    sNo: "9",
    centreName: "Akola-I",
    totalStudentBooked: "12",
  },
  {
    id: 10,
    sNo: "10",
    centreName: "Akola-II",
    totalStudentBooked: "12",
  },
  {
    id: 11,
    sNo: "11",
    centreName: "Akola-III",
    totalStudentBooked: "12",
  },
  {
    id: 12,
    sNo: "12",
    centreName: "Akola-III",
    totalStudentBooked: "12",
  },
];

export const PERMISION_AND_ROLE = {
  error: false,
  code: 200,
  message: "OK",
  data: [
    {
      name: "Control",
      slug: "control",
      id: 1,
      permissions: [
        {
          id: 19,
          name: "User Management",
          slug: "user-management",
        },
        {
          id: 20,
          name: "Bulk Notifications",
          slug: "bulk-notifications",
        },
        {
          id: 21,
          name: "Ticket Management",
          slug: "ticket-management",
        },
        {
          id: 22,
          name: "Query Management",
          slug: "query-management",
        },
        {
          id: 23,
          name: "Testimonial Management",
          slug: "testimonial-management",
        },
        {
          id: 24,
          name: "Registered Companies",
          slug: "registered-companies",
        },
      ],
    },
    {
      name: "CA-Jobs",
      slug: "ca-jobs",
      id: 2,
      permissions: [
        {
          id: 25,
          name: "Access Module",
          slug: "access-module",
        },
      ],
    },
    {
      name: "NQCA-Placement",
      slug: "nqca-placement",
      id: 3,
      permissions: [
        {
          id: 25,
          name: "Access Module",
          slug: "access-module",
        },
      ],
    },
    {
      name: "Overseas-Placement",
      slug: "overseas-placement",
      id: 4,
      permissions: [
        {
          id: 25,
          name: "Access Module",
          slug: "access-module",
        },
      ],
    },
    {
      name: "Career-Ascent",
      slug: "career-ascent",
      id: 5,
      permissions: [
        {
          id: 25,
          name: "Access Module",
          slug: "access-module",
        },
      ],
    },
    {
      name: "Women-Placement",
      slug: "women-placement",
      id: 6,
      permissions: [
        {
          id: 25,
          name: "Access Module",
          slug: "access-module",
        },
      ],
    },
  ],
};

export const CONFIGURE_INTERVIEW_DATES = [
  {
    id: 1,
    scheduleDate: "2023-12-19T05:11:46.000000Z",
    startTime: "2023-12-19T05:11:46.000000Z",
    endTime: "2023-12-19T05:11:46.000000Z",
    facilitiesNumber: 1,
    slotDurationInMinutes: "59",
  },
  {
    id: 2,
    scheduleDate: "2023-12-19T05:11:46.000000Z",
    startTime: "2023-12-19T05:11:46.000000Z",
    endTime: "2023-12-19T05:11:46.000000Z",
    facilitiesNumber: 1,
    slotDurationInMinutes: "59",
  },
  {
    id: 3,
    scheduleDate: "2023-12-19T05:11:46.000000Z",
    startTime: "2023-12-19T05:11:46.000000Z",
    endTime: "2023-12-19T05:11:46.000000Z",
    facilitiesNumber: 1,
    slotDurationInMinutes: "59",
  },
  {
    id: 4,
    scheduleDate: "2023-12-19T05:11:46.000000Z",
    startTime: "2023-12-19T05:11:46.000000Z",
    endTime: "2023-12-19T05:11:46.000000Z",
    facilitiesNumber: 1,
    slotDurationInMinutes: "59",
  },
];

export const COMPANIES_LIST = {
  meta: {
    total: 50,
    perPage: 10,
    currentPage: 1,
    lastPage: 5,
    from: 1,
    to: 10,
  },
  records: [
    {
      id: 50,
      name: "Google",
      user_name: "Silver-Grey Package",
      entity: "1@pAss_Word",
      description: "get all features",
      validity: 20,
      price: "200.00",
      status: 1,
      created_at: "2024-04-03T10:57:28.000000Z",
      updated_at: "2024-04-03T10:57:28.000000Z",
      created_by: "Shantanu Gupta",
    },
    {
      id: 49,
      name: "Microsoft",
      user_name: "Silver-Package",
      entity: "Abhay@123",
      description: "Silver-Package",
      validity: 10,
      price: "1000.00",
      status: 1,
      created_at: "2024-04-03T10:04:18.000000Z",
      updated_at: "2024-04-03T10:04:18.000000Z",
      created_by: "Shantanu Gupta",
    },
    {
      id: 48,
      name: "Appdynamics",
      user_name: "zero package",
      entity: "4@pAri_Rola",
      description: "AVV!r@D#$H%AVV!r@D#$H%",
      validity: 10,
      price: "0.00",
      status: 1,
      created_at: "2024-04-03T09:18:15.000000Z",
      updated_at: "2024-04-03T09:18:15.000000Z",
      created_by: "Shantanu Gupta",
    },
    {
      id: 47,
      name: "Appdynamics",
      user_name:
        "Others who use this device won\u2019t see your activity, so you can browse more privately. This won't cha",
      entity: "Abhay@123",
      description:
        "Others who use this device won\u2019t see your activity, so you can browse more privately. This won't cha",
      validity: 4,
      price: "5432.00",
      status: 1,
      created_at: "2024-04-01T12:08:42.000000Z",
      updated_at: "2024-04-01T12:08:42.000000Z",
      created_by: "Super Admin",
    },
    {
      id: 46,
      name: "Google",
      user_name:
        "Others who use this device won\u2019t see your activity, so you can browse more privately. This won't cha",
      entity: "4@pAri_Rola",
      description:
        "Others who use this device won\u2019t see your activity, so you can browse more privately. This won't cha",
      validity: 4,
      price: "5432.00",
      status: 1,
      created_at: "2024-04-01T12:08:29.000000Z",
      updated_at: "2024-04-01T12:08:29.000000Z",
      created_by: "Super Admin",
    },
    {
      id: 45,
      name: "Apple",
      user_name:
        "Others who use this device won\u2019t see your activity, so you can browse more privately. This won't cha",
      entity: "Rome@_1Paris",
      description:
        "Others who use this device won\u2019t see your activity, so you can browse more privately. This won't cha",
      validity: 4,
      price: "5432.00",
      status: 1,
      created_at: "2024-04-01T11:24:37.000000Z",
      updated_at: "2024-04-01T11:24:37.000000Z",
      created_by: "Super Admin",
    },
    {
      id: 44,
      name: "Meta",
      user_name:
        "Others who use this device won\u2019t see your activity, so you can browse more privately. This won't cha",
      entity: "6@pAri_Rola",
      description:
        "Others who use this device won\u2019t see your activity, so you can browse more privately. This won't cha",
      validity: 4,
      price: "5432.00",
      status: 1,
      created_at: "2024-04-01T11:23:11.000000Z",
      updated_at: "2024-04-01T11:23:11.000000Z",
      created_by: "Super Admin",
    },
    {
      id: 43,
      name: "Faang",
      user_name: "1111",
      entity: "4@pAri_Rola",
      description: "11",
      validity: 1,
      price: "0.00",
      status: 0,
      created_at: "2024-03-28T12:42:48.000000Z",
      updated_at: "2024-04-03T08:32:13.000000Z",
      created_by: "Abhay 123",
    },
    {
      id: 42,
      name: "Appdynamics",
      user_name: "Dummy",
      entity: "4@pAri_Rola",
      description:
        "DummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummyDummy",
      validity: 1,
      price: "1.00",
      status: 0,
      created_at: "2024-03-28T12:01:56.000000Z",
      updated_at: "2024-04-03T08:34:06.000000Z",
      created_by: "Abhay 123",
    },
    {
      id: 41,
      name: "Microsoft",
      user_name: "Test",
      entity: "4@pAri_Rola",
      description:
        "sdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddsdaassdddddddddddddddddddddd",
      validity: 1,
      price: "1.00",
      status: 1,
      created_at: "2024-03-28T12:01:17.000000Z",
      updated_at: "2024-03-28T12:01:17.000000Z",
      created_by: "Abhay 123",
    },
  ],
};
